select * from AddedSongs;
select * from Albums;
select * from Artists;
select * from Collaborations;
select * from LikedSongs;
select * from Playlists;
select * from Songs;
select * from Subscriptions;
select * from Users;